// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs3qHtQkSrrGrb50JgPHJfUYajUkZWs58',
    appId: '1:490252354873:web:10a835d110ad5071d9d4e8',
    messagingSenderId: '490252354873',
    projectId: 'flutter-everytime',
    authDomain: 'flutter-everytime.firebaseapp.com',
    storageBucket: 'flutter-everytime.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQMpzjj3V5bWVCGh4r2WJ6bHBHLUudBtg',
    appId: '1:490252354873:android:5673d999c50a4057d9d4e8',
    messagingSenderId: '490252354873',
    projectId: 'flutter-everytime',
    storageBucket: 'flutter-everytime.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBy9ABVyUxIYMfGCv-ooab_7X4szB2I5Q',
    appId: '1:490252354873:ios:c4da836a2dcd14d1d9d4e8',
    messagingSenderId: '490252354873',
    projectId: 'flutter-everytime',
    storageBucket: 'flutter-everytime.appspot.com',
    iosBundleId: 'com.example.everytime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBy9ABVyUxIYMfGCv-ooab_7X4szB2I5Q',
    appId: '1:490252354873:ios:3643794d8754de16d9d4e8',
    messagingSenderId: '490252354873',
    projectId: 'flutter-everytime',
    storageBucket: 'flutter-everytime.appspot.com',
    iosBundleId: 'com.example.everytime.RunnerTests',
  );
}
